### ISSUE TITLE
wp-clarkson.com website

### ISSUE THREAD

**Issue by Mike-Hermans** [level-level/Clarkson-Theme#18]
Hier een (eventuele) lijst met issues op wp-clarkson.com
- [ ] Wanneer je de pagina voor het eerst bezoekt op mobile en de pagina's zijn nog niet gecached, gaat het wisselen van pagina's niet erg soepel. Als je dit eenmaal hebt gedaan is er die sessie geen probleem meer, maar als je opnieuw de website laad gebeurd hetzelfde weer. Ik gok dat dit komt omdat de animatie sneller is dan het laden van de nieuwe pagina, misschien dat de pagina wit kan blijven tot de andere pagina is geladen, of we vertragen de animatie.

- [ ] Betere site description in _config.yml
- [ ] Favicon toevoegen
- [ ] Voorbeeld met single.php en eenvoudiger single.twig
- [ ] Voorbeeld hoe je ACF kan toepassen
- [ ] Voorbeeld hoe je Gravity Forms kan toepassen

**Comment by jmslbam** [comment]
Alles done! :)
