### ISSUE TITLE
Installation - No package.json

### ISSUE THREAD

**Issue by JanNovakFRI** [level-level/Clarkson-Theme#29]
Hello,

project looks really interesting to me, but I have already stuck at the first step - installation. How can I install anything if there is no package.json.

Regards
Jan

**Comment by jmslbam** [comment]
Hi Jan,

I'm glad it looks interesting. You can find the `package.json` within the `/development` directory.
If you run `npm install` there everything will be installed.

Regards,

Jaime

**Comment by jmslbam** [comment]
If you need any further help, just re-open this issue.

Jaime

**Comment by jmslbam** [comment]
I just added this information to the documentation in the repo and on the site. Thank you for pointing this out! Have a nice evening.
